serverAddr = "spine.healthit.cn"
serverPort = 5001

[auth]
method = "token"
token = "WhatsYourMissionInShanghai"

[[proxies]]
name = "infer_server"
type = "tcp"
localIP = "127.0.0.1"
localPort = 8000
remotePort = 15443
